#!/usr/bin/env python3
"""Generate docs/config_catalog.md from workflow/config/config.yaml."""

from __future__ import annotations

from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML required")

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "workflow" / "config" / "config.yaml"
OUT = ROOT / "docs" / "config_catalog.md"


def _flatten(prefix: str, obj: object, rows: list[tuple[str, str, str]]) -> None:
    if isinstance(obj, dict):
        for key, val in obj.items():
            path = f"{prefix}.{key}" if prefix else key
            if isinstance(val, dict):
                _flatten(path, val, rows)
            else:
                rows.append((path, _fmt(val), _type_name(val)))
    else:
        rows.append((prefix, _fmt(obj), _type_name(obj)))


def _fmt(val: object) -> str:
    if val is None:
        return "`null`"
    if isinstance(val, bool):
        return f"`{str(val).lower()}`"
    if isinstance(val, (int, float)):
        return f"`{val}`"
    if isinstance(val, str):
        if "/" in val or len(val) > 48:
            return f"`{val}`"
        return f"`{val}`"
    if isinstance(val, list):
        return "`" + ", ".join(str(x) for x in val) + "`"
    return f"`{val}`"


def _type_name(val: object) -> str:
    if val is None:
        return "null"
    if isinstance(val, bool):
        return "bool"
    if isinstance(val, int):
        return "int"
    if isinstance(val, float):
        return "float"
    if isinstance(val, list):
        return "list"
    return "string"


def main() -> None:
    cfg = yaml.safe_load(CONFIG.read_text()) or {}
    rows: list[tuple[str, str, str]] = []
    _flatten("", cfg, rows)

    lines = [
        "# Configuration catalog",
        "",
        "Auto-generated from [`workflow/config/config.yaml`]"
        "(https://github.com/phindagijimana/dkt_connectome/blob/main/dwi_pipeline/workflow/config/config.yaml).",
        "",
        "Regenerate after editing defaults:",
        "",
        "```bash",
        "python3 dwi_pipeline/scripts/generate_config_catalog.py",
        "```",
        "",
        "Override locally in `workflow/config/config.local.yaml` (gitignored) or via Snakemake `--config`.",
        "JSON Schema: [Schema reference](schema_reference.md).",
        "",
        "| Key | Default | Type |",
        "|-----|---------|------|",
    ]
    for key, default, typ in rows:
        lines.append(f"| `{key}` | {default} | {typ} |")
    lines.append("")

    header = (
        "<!-- AUTO-GENERATED by scripts/generate_config_catalog.py — do not edit by hand. -->\n\n"
    )
    OUT.write_text(header + "\n".join(lines))
    print(f"Wrote {OUT} ({len(rows)} keys)")


if __name__ == "__main__":
    main()
