#!/usr/bin/env python3
"""Write docs/maintainer/container_digests.md from cached Apptainer images."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DWI_PIPELINE = SCRIPT_DIR.parent
OUT = DWI_PIPELINE / "docs" / "maintainer" / "container_digests.md"
APP_JSON = DWI_PIPELINE / "app.json"


def pipeline_version() -> str:
    if APP_JSON.is_file():
        return json.loads(APP_JSON.read_text()).get("PipelineVersion", "0.2.0")
    return "0.2.0"


def main() -> None:
    cache = Path(
        __import__("os").environ.get("DKT_CONTAINER_CACHE", Path.home() / ".cache" / "dkt-connectome" / "containers")
    ).expanduser()
    version = pipeline_version()
    proc = subprocess.run(
        [
            sys.executable,
            str(SCRIPT_DIR / "container_install.py"),
            "digests",
            "--cache",
            str(cache),
            "--mode",
            "all",
            "--format",
            "markdown",
            "--version",
            version,
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    header = (
        "<!-- Auto-generated by scripts/generate_container_digests_md.py — do not edit by hand. -->\n\n"
    )
    OUT.write_text(header + proc.stdout)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
