#!/usr/bin/env python3
"""Generate an MRtrix labelconvert LUT for the DKT parcellation.

FastSurfer's aparc+aseg.mgz is the Desikan-Killiany-Tourville (DKT) atlas,
which by protocol omits bankssts, the frontal pole and the temporal pole.
Running labelconvert with MRtrix's Desikan-Killiany LUT (fs_default.txt,
84 nodes) against a FastSurfer segmentation therefore leaves 6 nodes with
no voxels, and tck2connectome emits 6 all-zero rows/columns.

This script derives fs_dkt.txt (78 nodes) from fs_default.txt by dropping
those 6 regions and renumbering the remainder contiguously, so a FastSurfer
run yields a connectome with no structurally empty nodes.

Note that fs_default.txt maps two names to the same node index for the
thalamus ("Left-Thalamus" and "Left-Thalamus-Proper"), covering both the
FreeSurfer 6 and FreeSurfer 7 naming. That aliasing is preserved.

Usage:
    python3 make_dkt_lut.py [--in fs_default.txt] [--out fs_dkt.txt] [--check]
"""

from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path

# Regions in the Desikan-Killiany atlas that the DKT protocol does not define.
DKT_EXCLUDED = {
    "ctx-lh-bankssts",
    "ctx-rh-bankssts",
    "ctx-lh-frontalpole",
    "ctx-rh-frontalpole",
    "ctx-lh-temporalpole",
    "ctx-rh-temporalpole",
}

HEADER = """\
# Lookup table for extracting the DKT (Desikan-Killiany-Tourville) grey matter
# parcellation from a FastSurfer segmentation, for use with MRtrix labelconvert.
#
# Generated by dwi_pipeline/scripts/make_dkt_lut.py from fs_default.txt.
# Do not edit by hand; regenerate instead.
#
# Derived from MRtrix3's fs_default.txt (Desikan-Killiany, 84 nodes) by removing
# the 6 regions the DKT protocol does not define -- bankssts, frontal pole and
# temporal pole, bilaterally -- and renumbering the remaining {n} nodes
# contiguously. Use this LUT when the segmentation came from FastSurfer, whose
# aparc+aseg.mgz is aparc.DKTatlas+aseg.mapped.mgz; use fs_default.txt for a
# FreeSurfer recon-all segmentation.
"""


def parse_lut(path: Path):
    """Return (groups, excluded_names).

    groups maps original index -> list of (abbrev, fs_name, rgba tuple),
    preserving the order entries appear in the file. Several names may share
    one index; MRtrix treats them as aliases for the same node.
    """
    groups: "OrderedDict[int, list]" = OrderedDict()
    for lineno, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.split("#")[0].strip()
        if not line:
            continue
        parts = line.split()
        if not parts[0].isdigit():
            continue
        index = int(parts[0])
        if index == 0:
            continue
        if len(parts) < 7:
            raise ValueError(f"{path}:{lineno}: expected 7 columns, got {len(parts)}")
        abbrev, fs_name = parts[1], parts[2]
        rgba = tuple(parts[3:7])
        groups.setdefault(index, []).append((abbrev, fs_name, rgba))
    if not groups:
        raise ValueError(f"{path}: no LUT entries found")
    return groups


def build_dkt(groups):
    """Drop DKT-excluded nodes and renumber the rest from 1."""
    kept, dropped = [], []
    for index in sorted(groups):
        entries = groups[index]
        names = {fs_name for _, fs_name, _ in entries}
        if names & DKT_EXCLUDED:
            # A node is either entirely excluded or entirely kept; a partial
            # overlap would mean the alias grouping is not what we assume.
            if not names <= DKT_EXCLUDED:
                raise ValueError(
                    f"node {index} mixes DKT-excluded and retained names: {sorted(names)}"
                )
            dropped.append((index, entries))
            continue
        kept.append((index, entries))

    missing = DKT_EXCLUDED - {n for _, entries in dropped for _, n, _ in entries}
    if missing:
        raise ValueError(f"expected regions not present in input LUT: {sorted(missing)}")

    return [(new, old, entries) for new, (old, entries) in enumerate(kept, start=1)], dropped


def format_lut(rows) -> str:
    out = [HEADER.format(n=len(rows)), "", f"{0:<5} {'???':<7} {'Unknown':<31} 0   0   0   0", ""]
    for new_index, _old_index, entries in rows:
        for abbrev, fs_name, rgba in entries:
            r, g, b, a = rgba
            out.append(f"{new_index:<5} {abbrev:<7} {fs_name:<31} {r:<3} {g:<3} {b:<3} {a}")
    return "\n".join(out) + "\n"


def main() -> int:
    here = Path(__file__).resolve().parent
    lut_dir = here.parent / "containers" / "connectome" / "mrtrix_lut"

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in", dest="src", type=Path, default=lut_dir / "fs_default.txt")
    ap.add_argument("--out", dest="dst", type=Path, default=lut_dir / "fs_dkt.txt")
    ap.add_argument("--check", action="store_true",
                    help="verify the existing output is up to date instead of writing it")
    args = ap.parse_args()

    groups = parse_lut(args.src)
    rows, dropped = build_dkt(groups)
    text = format_lut(rows)

    print(f"input  {args.src}: {len(groups)} nodes")
    print(f"dropped {len(dropped)} DKT-excluded nodes:")
    for index, entries in dropped:
        print(f"    {index:>3} {entries[0][0]:<7} {entries[0][1]}")
    print(f"output {args.dst}: {len(rows)} nodes")

    if args.check:
        if not args.dst.exists():
            print(f"ERROR: {args.dst} does not exist", file=sys.stderr)
            return 1
        if args.dst.read_text() != text:
            print(f"ERROR: {args.dst} is stale; rerun without --check", file=sys.stderr)
            return 1
        print("up to date")
        return 0

    args.dst.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
