#!/usr/bin/env python3
"""
list_subjects.py — scan a BIDS root and emit subjects.tsv.

Usage:
    python workflow/scripts/list_subjects.py /path/to/BIDS > config/subjects.tsv
    python workflow/scripts/list_subjects.py /path/to/BIDS --require-dwi
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("bids_root", type=Path)
    p.add_argument(
        "--require-dwi",
        action="store_true",
        help="Only emit subjects with at least one *.nii(.gz) under dwi/.",
    )
    p.add_argument(
        "--require-t1w",
        action="store_true",
        help="Only emit subjects with at least one *_T1w.nii(.gz) under anat/.",
    )
    args = p.parse_args()

    if not args.bids_root.is_dir():
        print(f"error: not a directory: {args.bids_root}", file=sys.stderr)
        return 1

    print("# Subjects discovered from", args.bids_root)
    print("# Generated by workflow/scripts/list_subjects.py")
    for entry in sorted(args.bids_root.iterdir()):
        if not (entry.is_dir() and entry.name.startswith("sub-")):
            continue
        sid = entry.name.removeprefix("sub-")
        if args.require_dwi and not any(
            "/dwi/" in str(p) for p in entry.rglob("*.nii*")
        ):
            continue
        if args.require_t1w and not any(
            "/anat/" in str(p) and "_T1w" in p.name for p in entry.rglob("*.nii*")
        ):
            continue
        print(sid)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
